import { Header } from './_components/Header'
import { appFontVariableClassNames } from './fonts'

import type { Metadata } from 'next'

import './styles/main.scss'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode,
}>) {
  return (
    <html lang="en" className={appFontVariableClassNames}>
      <body>
        <Header />

        {children}
      </body>
    </html>
  )
}
