import { Footer } from './_components/Footer'
import { Header } from './_components/Header'
import { appFontVariableClassNames } from './fonts'
import s from './layout.module.scss'

import type { Metadata } from 'next'

import './styles/main.scss'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode,
}>) {
  return (
    <html lang="en" className={appFontVariableClassNames}>
      <body className={s.body}>
        <Header />

        <div>{children}</div>

        <Footer />
      </body>
    </html>
  )
}
