import { Suspense } from 'react'

import { Footer } from './_components/Footer'
import { Header } from './_components/Header'
import { appFontVariableClassNames } from './fonts'
import s from './layout.module.scss'

import type { Metadata, Viewport } from 'next'

import './styles/main.scss'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const viewport: Viewport = {
  themeColor: '#14151c',
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  colorScheme: 'only light',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode,
}>) {
  return (
    <html lang="en" className={appFontVariableClassNames}>
      <body className={s.body}>
        <Header />

        <div>{children}</div>

        <Suspense fallback={null}>
          <Footer />
        </Suspense>
      </body>
    </html>
  )
}
